apiVersion: v1
kind: Namespace
metadata:
  name: curl
  labels:
    openservicemesh.io/monitored-by: osm
  annotations:
    openservicemesh.io/metrics: enabled
    openservicemesh.io/sidecar-injection: enabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: curl
  namespace: curl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl
  namespace: curl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl
  template:
    metadata:
      labels:
        app: curl
    spec:
      serviceAccountName: curl
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
      containers:
        - image: curlimages/curl
          imagePullPolicy: IfNotPresent
          name: curl
          command: ["sleep", "365d"]
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
              memory: 500M
