# Create bookbuyer Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookbuyer
  namespace: bookbuyer

---
apiVersion: v1
kind: Service
metadata:
  name: bookbuyer
  namespace: "bookbuyer"
  labels:
    app: bookbuyer
spec:
  ports:
    - port: 14001
      name: http-bookbuyer
  selector:
    app: bookbuyer

---
# Create bookbuyer Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookbuyer
  namespace: bookbuyer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookbuyer
      version: v1
  template:
    metadata:
      labels:
        app: bookbuyer
        version: v1
    spec:
      serviceAccountName: bookbuyer
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
      containers:
        - name: bookbuyer
          image: openservicemesh/bookbuyer:v1.0.0
          imagePullPolicy: Always
          command: ["/bookbuyer"]
          env:
            - name: "BOOKSTORE_NAMESPACE"
              value: bookstore
            - name: "BOOKSTORE_SVC"
              value: bookstore
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
              memory: 500M
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookbuyer
  namespace: bookbuyer
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /bookbuyer(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: bookbuyer
                port:
                  number: 14001
  ingressClassName: nginx
---
kind: IngressBackend
apiVersion: policy.openservicemesh.io/v1alpha1
metadata:
  name: bookbuyer
  namespace: bookbuyer
spec:
  backends:
    - name: bookbuyer
      port:
        number: 14001
        protocol: http
  sources:
    - kind: Service
      namespace: ingress-nginx
      name: ingress-nginx-controller
---

